name: main workflow
on: [push, workflow_dispatch]
jobs:
  jobcodesetup:
    runs-on: ubuntu-latest
    steps:
    - name: get code
      uses: actions/checkout@v3
    - name: install NodeJs
      uses: actions/setup-node@v3
    - name: install dependencies
      run: npm ci
  jobbuildprj:
    needs: jobcodesetup
    runs-on: ubuntu-latest
    steps:
    - name: build project
      run: npm run build
  jobunittest:
    needs: jobbuildprj
    runs-on: ubuntu-latest
    steps:
    - name: unit test
      run: npm test  
  jobdeployment:
    needs: jobunittest
    runs-on: ubuntu-latest
    steps:
    - name: deployment
      run: echo "deploying"