name: main workflow
on: [push, workflow_dispatch]
jobs:
  codesetup:
    runs-on: ubuntu-latest
    steps:
    - name: get code
      uses: actions/checkout@v3
    - name: install NodeJs
      uses: actions/setup-node@v3
    - name: install dependencies
      run: npm ci
  buildprj:
    needs: codesetup
    runs-on: ubuntu-latest
    steps:
    - name: build project
      run: npm run build
  unittest:
    needs: buildprj
    runs-on: ubuntu-latest
    steps:
    - name: unit test
      run: npm test  
  deployment:
    needs: unittest
    runs-on: ubuntu-latest
    steps:
    - name: deployment
      run: echo "deploying"